name: Artifact workflow-02

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: File made by Github Actions ubuntu
        run: touch actions-file.log

      - name: 디버그: 현재 디렉토리 목록 출력
        run: ls -al

      - name: From Github Actions to AWS EC2 through SCP
        uses: appleboy/scp-action@v1
        with: 
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "./actions-file.log"
          target: /home/ubuntu
